#!/usr/bin/env ruby
# parameters: revision1, revision 2, branch
require '/usr/local/share/git_commit_notifier/lib/commit_hook'

config = YAML.parse_file(File.dirname(__FILE__) + '/commit_notifier_config.yml')

if ARGV[0].nil?
  param = STDIN.gets.strip.split
  CommitHook.run config, param[0], param[1], param[2]
else
  CommitHook.run config, ARGV[0], ARGV[1], ARGV[2]
end

