require 'rake'
require 'rake/testtask'

task :default => [:test]

task :test do |test|
  Rake::TestTask.new do |t|
    t.libs << "test"
    t.test_files = FileList['test/*.rb']
    t.verbose = true
  end
end
